MvcKutuphaneSistemi/Controllers/OduncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneSistemi.Models.Entity;

namespace MvcKutuphaneSistemi.Controllers
{
    public class OduncController : Controller
    {
        // GET: Odunc
        MvcKutuphaneEntities db = new MvcKutuphaneEntities();
        public ActionResult Index()
        {
            var hareket = db.Hareketler.Where(x => x.IslemDurum == false).ToList();
            return View(hareket);
        }
        [HttpGet]
        public ActionResult OduncVer()
        {
            List<SelectListItem> deger1 = (from x in db.Uyeler.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UyeAD + " " + x.UyeSoyad,
                                               Value = x.UyeID.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from k in db.Kitaplar.Where(z => z.Durum == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = k.KitapAD,
                                               Value = k.KitapID.ToString()

                                           }).ToList();

            List<SelectListItem> deger3 = (from p in db.Personel.ToList()
                                           select new SelectListItem
                                           {
                                               Text = p.PersonelAdSoyad,
                                               Value = p.PersonelID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult OduncVer(Hareketler h)
        {
            var d1 = db.Uyeler.Where(x => x.UyeID == h.Uyeler.UyeID).FirstOrDefault();
            var d2 = db.Kitaplar.Where(k => k.KitapID == h.Kitaplar.KitapID).FirstOrDefault();
            var d3 = db.Personel.Where(p => p.PersonelID == h.Personel.PersonelID).FirstOrDefault();
            h.Uyeler = d1;
            h.Kitaplar = d2;
            h.Personel = d3;
            var hareket = db.Hareketler.Add(h);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Odunciade(int id)
        {
            var odn = db.Hareketler.Find(id);
            DateTime d1 = DateTime.Parse(odn.iadeTarihi.ToString());
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;
            ViewBag.dgr1 = d3.TotalDays;
            return View("Odunciade", odn);
        }
        public ActionResult OduncGuncelle(Hareketler p)
        {
            var hrkt = db.Hareketler.Find(p.HareketID);
            hrkt.UyeGetirTarih = p.UyeGetirTarih;
            hrkt.IslemDurum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphaneSistemi/Views/Odunc/Index.cshtml
@using MvcKutuphaneSistemi.Models.Entity
@model List<Hareketler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h2>Ödünç Kitap Listesi</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>İşlem İD</th>
        <th>Kitap Adı</th>
        <th>Üye Adı Soyadı</th>
        <th>Personel Adı Soyadı</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>İade Al</th>
    </tr>
    @foreach (var hrkt in Model)
    {
        <tr>
            <th>@hrkt.HareketID</th>
            <td>@hrkt.Kitaplar.KitapAD</td>
            <td>@hrkt.Uyeler.UyeAD&nbsp @hrkt.Uyeler.UyeSoyad</td>
            <td>@hrkt.Personel.PersonelAdSoyad</td>
            <td>@Convert.ToDateTime(hrkt.AlisTarihi).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(hrkt.iadeTarihi).ToString("dd/MM/yyyy")</td>
            <td><a href="/Odunc/Odunciade/@hrkt.HareketID" class="btn btn-default" style="background-color:#139089; color:white">Kitabı İade Et</a></td>
        </tr>
    }
</table>

MvcKutuphaneSistemi/Views/Odunc/OduncVer.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Hareketler
@{
    ViewBag.Title = "OduncVer";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
<form class="form-group" method="post">
    <div style="margin-top:15px;">
        <label>Üye İD</label>
        @Html.DropDownListFor(x => x.Uyeler.UyeID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <label>Kitap İD</label>
        @Html.DropDownListFor(k => k.Kitaplar.KitapID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <label>Personel İD</label>
        @Html.DropDownListFor(p => p.Personel.PersonelID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <label>Kitap Alış Tarihi</label>
        <input class="form-control" name="AlisTarihi" value="@DateTime.Now.ToShortDateString()" type="text" readonly="readonly" />
    </div>
    <div style="margin-top:15px;">
        <label>Kitap İade Tarihi</label>
        <input class="form-control" name="iadeTarihi" value="@DateTime.Now.AddDays(7).ToShortDateString()" type="text" readonly="readonly" />
    </div>

    <div style="margin-top:15px;">
        <button class="btn btn-warning">Ödünç Kİtap Ver</button>
    </div>
    <input type="hidden" value="false" name="IslemDurum" />
</form>

MvcKutuphaneSistemi/Views/Odunc/Odunciade.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Hareketler
@{
    ViewBag.Title = "Odunciade";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
@using (Html.BeginForm("OduncGuncelle", "Odunc", FormMethod.Post))
{
    <div class="form-group">
        <label>Hareket İD</label>
        @Html.TextBoxFor(odn => odn.HareketID, new { @class = "form-control" })
        <br />
        <label>Kitap Adı</label>
        @Html.TextBoxFor(odn => odn.Kitaplar.KitapAD, new { @class = "form-control" })
        <br />
        <label>Üye Adı</label>
        @Html.TextBoxFor(odn => odn.Uyeler.UyeAD, new { @class = "form-control" })
        <br />
        <label>Personel Adı Soyadı</label>
        @Html.TextBoxFor(odn => odn.Personel.PersonelAdSoyad, new { @class = "form-control" })
        <br />
        <label>Alış Tarihi</label>
        @Html.TextBoxFor(odn => odn.AlisTarihi, "{0:dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>İade Tarihi</label>
        @Html.TextBoxFor(odn => odn.iadeTarihi, "{0:dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Üyenin Getirdiği Tarihi</label>
        <input type="text" name="UyeGetirTarih" value="@DateTime.Now.ToShortDateString()" class="form-control" />
        <br />
        <label>Geç Gelen Gün Sayısı</label>
        <input type="text" class="form-control" id="Gecinput" value="@ViewBag.dgr1" />
        <br />
        <div>
            <button class="btn btn-default" style="background-color:#0094ff; color:white;">Ödünç Kitabı Geri Al</button>
        </div>
    </div>
}