MvcKutuphaneSistemi/Models/Entity/Kategoriler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategoriler()
        {
            this.Kitaplar = new HashSet<Kitaplar>();
        }
    
        public byte KategoriID { get; set; }
        public string KategoriAD { get; set; }
        public Nullable<bool> KategoriDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
    }
}

MvcKutuphaneSistemi/Controllers/KategorilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneSistemi.Models.Entity;

namespace MvcKutuphaneSistemi.Controllers
{
    public class KategorilerController : Controller
    {
        // GET: Kategoriler
        MvcKutuphaneEntities db = new MvcKutuphaneEntities();
        public ActionResult Index()
        {
            var degerler = db.Kategoriler.Where(x => x.KategoriDurum == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(Kategoriler p1)
        {
            db.Kategoriler.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult KategoriSil(int id)
        {
            var kategori = db.Kategoriler.Find(id);
            //BurasıSİler 
            //db.Kategoriler.Remove(kategori);
            //Burası PASif HAle getirir
            kategori.KategoriDurum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var kategori = db.Kategoriler.Find(id);
            return View("KategoriGetir", kategori);
        }
        public ActionResult KategoriGuncelle(Kategoriler p1)
        {
            var ktg = db.Kategoriler.Find(p1.KategoriID);
            ktg.KategoriAD = p1.KategoriAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphaneSistemi/Views/Kategoriler/Index.cshtml
@using MvcKutuphaneSistemi.Models.Entity
@model List<Kategoriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>Kategori İD</th>
        <th>Kategori ADI</th>
        <th>Kategori Sil</th>
        <th>Kategori Güncelle</th>
    </tr>
    @foreach (var ktg in Model)
    {
        <tr>
            <th>@ktg.KategoriID</th>
            <td>@ktg.KategoriAD</td>
            <td><a href="/Kategoriler/KategoriSil/@ktg.KategoriID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kategoriler/KategoriGetir/@ktg.KategoriID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }

</table>
<a href="/Kategoriler/KategoriEkle/" class="btn btn-primary">Yeni Kategori Ekle</a>

MvcKutuphaneSistemi/Views/Kategoriler/KategoriEkle.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Kategoriler
@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
<form class="form-group" method="post">
    <div>
        <label>Kategori Adı:</label>
        <input type="text" name="KategoriAD" class="form-control" />
    </div>
    <div style="margin-top:15px;">
        <button class="btn btn-info">Kategori Ekle</button>
    </div>
</form>

MvcKutuphaneSistemi/Views/Kategoriler/KategoriGetir.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Kategoriler
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
@using (Html.BeginForm("KategoriGuncelle", "Kategoriler", FormMethod.Post))
{
    <div>
        <label>Kategori İD:</label>
        @Html.TextBoxFor(k => k.KategoriID, new { @class = "form-control" })
        <br />
        <label>Kategori Adı:</label>
        @Html.TextBoxFor(k => k.KategoriAD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <button class="btn btn-warning">Kategori Güncelle</button>
    </div>
}