MvcKutuphaneSistemi/Models/Entity/Personel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Hareketler = new HashSet<Hareketler>();
        }
    
        public byte PersonelID { get; set; }
        public string PersonelAdSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hareketler> Hareketler { get; set; }
    }
}

MvcKutuphaneSistemi/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneSistemi.Models.Entity;

namespace MvcKutuphaneSistemi.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        MvcKutuphaneEntities db = new MvcKutuphaneEntities();
        public ActionResult Index()
        {
            var pers = db.Personel.ToList();
            return View(pers);
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(Personel p)
        {
            if (!ModelState.IsValid)
            {
                return View("PersonelEkle");
            }
            var pers = db.Personel.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelSil(int id)
        {
            var pers = db.Personel.Find(id);
            db.Personel.Remove(pers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetir(int id)
        {
            var pers = db.Personel.Find(id);
            return View("PersonelGetir", pers);
        }
        public ActionResult PersonelGuncelle(Personel p)
        {
            var pers = db.Personel.Find(p.PersonelID);
            pers.PersonelAdSoyad = p.PersonelAdSoyad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphaneSistemi/Views/Personel/Index.cshtml
@using MvcKutuphaneSistemi.Models.Entity
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>Personel İD</th>
        <th>Personel Adı Soyadı</th>
        <th>Personel Sil</th>
        <th>Personel Günelle</th>
    </tr>
    @foreach (var pers in Model)
    {
        <tr>
            <td>@pers.PersonelID</td>
            <td>@pers.PersonelAdSoyad</td>
            <td><a href="/Personel/PersonelSil/@pers.PersonelID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Personel/PersonelGetir/@pers.PersonelID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Personel/PersonelEkle/" class="btn btn-primary">Yeni Personel Ekle</a>

MvcKutuphaneSistemi/Views/Personel/PersonelEkle.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
<form class="form-group" method="post">
    <div>
        <label>Personel Adı Soyadı</label>
        @Html.TextBoxFor(p => p.PersonelAdSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.PersonelAdSoyad, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px;">
        <button class="btn btn-warning">Personel Ekle</button>
    </div>
</form>

MvcKutuphaneSistemi/Views/Personel/PersonelGetir.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
    <div>
        <label>Personel İD</label>
        @Html.TextBoxFor(p => p.PersonelID, new { @class = "form-control" })
        <br />
        <label>Personel Adı Soyadı</label>
        @Html.TextBoxFor(p => p.PersonelAdSoyad, new { @class = "form-control" })


    </div>
    <div style="margin-top:15px;">
        <button class="btn btn-warning">Personel Bilgilerini Güncelle</button>
    </div>
}