MvcKutuphaneSistemi/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneSistemi.Models.Entity;
namespace MvcKutuphaneSistemi.Controllers
{
    public class YazarController : Controller
    {
        // GET: Yazar
        MvcKutuphaneEntities db = new MvcKutuphaneEntities();
        public ActionResult Index()
        {
            var yzr = db.Yazarlar.ToList();
            return View(yzr);
        }
        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YazarEkle(Yazarlar p1)
        {
            if (ModelState.IsValid)
            {
                var yzr = db.Yazarlar.Add(p1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("YazarEKle");
        }
        public ActionResult YazarSil(int id)
        {
            var yzr = db.Yazarlar.Find(id);
            db.Yazarlar.Remove(yzr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarGetir(int id)
        {
            var yzr = db.Yazarlar.Find(id);
            return View("YazarGetir", yzr);
        }
        public ActionResult YazarGuncelle(Yazarlar p1)
        {
            var yzr = db.Yazarlar.Find(p1.YazarID);
            yzr.YazarAD = p1.YazarAD;
            yzr.YazarSoyad = p1.YazarSoyad;
            yzr.Detay = p1.Detay;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarKitap(int id)
        {
            var yazar = db.Kitaplar.Where(x => x.YazarID == id).ToList();
            var yzr = db.Yazarlar.Where(x => x.YazarID == id).Select(z => z.YazarAD + " " + z.YazarSoyad).FirstOrDefault();
            ViewBag.dgr1 = yzr;
            return View(yazar);
        }
    }
}

MvcKutuphaneSistemi/Views/Yazar/Index.cshtml
@using MvcKutuphaneSistemi.Models.Entity
@model List<Yazarlar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>İD</th>
        <th>Yazar Adı</th>
        <th>Yazar Soyadı</th>
        <th>Yazar Sil</th>
        <th>Yazar Güncelle</th>
        <th>Yazar'ın Kitapları</th>
    </tr>
    @foreach (var yzr in Model)
    {
    <tr>
        <th>@yzr.YazarID</th>
        <td>@yzr.YazarAD</td>
        <td>@yzr.YazarSoyad</td>
        <td>@Html.ActionLink("Sil", "YazarSil", new { id = yzr.YazarID }, new { @class = "btn btn-danger", onclick = "return confirm('Yazarı Silmek İstediğinden Emin misin?')" })</td>
        <td><a href="/Yazar/YazarGetir/@yzr.YazarID" class="btn btn-success">Güncelle</a></td>
        <td><a href="/Yazar/YazarKitap/@yzr.YazarID" class="btn btn-outline-secondary">Yazar'ın Kitapları</a></td>
    </tr>
    }

</table>
<a href="/Yazar/YazarEkle" class="btn btn-primary">Yeni Yazar Ekle</a>

MvcKutuphaneSistemi/Views/Yazar/YazarEkle.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Yazarlar
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
<form class="form-group" method="post">
    <div>
        <label>Yazar Adı</label>
        @Html.TextBoxFor(y => y.YazarAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(y => y.YazarAD, "", new { @style = "color:red" })
        <br />
        <label>Yazar Soyadı</label>
        @Html.TextBoxFor(y => y.YazarSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(y => y.YazarSoyad, "", new { @style = "color:red" })
        <br />
        <label>Yazar Detay</label>
        @Html.TextAreaFor(y => y.Detay, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <button class="btn btn-warning">Yazar Ekle</button>
    </div>

</form>

MvcKutuphaneSistemi/Views/Yazar/YazarGetir.cshtml
@model MvcKutuphaneSistemi.Models.Entity.Yazarlar
@{
    ViewBag.Title = "YazarGetir";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<br />
@using (Html.BeginForm("YazarGuncelle", "Yazar", FormMethod.Post))
{
    <div>
        <label>Yazar İD</label>
        @Html.TextBoxFor(y => y.YazarID, new { @class = "form-control" })
        <br />
        <label>Yazar Adı</label>
        @Html.TextBoxFor(y => y.YazarAD, new { @class = "form-control" })
        <br />
        <label>Yazar Soyadı</label>
        @Html.TextBoxFor(y => y.YazarSoyad, new { @class = "form-control" })
        <br />
        <label>Detay</label>
        @Html.TextAreaFor(y => y.Detay, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px;">
        <button class="btn btn-warning">Yazar Bilgilerini Güncelle</button>
    </div>
}

MvcKutuphaneSistemi/Views/Yazar/YazarKitap.cshtml
@using MvcKutuphaneSistemi.Models.Entity;
@model List<Kitaplar>
@{
    ViewBag.Title = "YazarKitap";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h2>Yazar'ın Adı ve Soyadı : @ViewBag.dgr1 </h2>
<br />
<table class="table table-active">
    <tr>
        <th>Kitap ID</th>
        <th>Kitap Adı</th>
        <th>Kategorisi</th>
        <th>Yayın Evi</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <th>@x.KitapID</th>
            <td>@x.KitapAD</td>
            <td>@x.Kategoriler.KategoriAD</td>
            <td>@x.YayinEvi</td>
        </tr>
    }
</table>